-- INSERT generado a partir de BEDCA (nombres en español)
-- category_id / default_unit_id / is_prepared asignados por heurística automática.
-- Pensado para entorno de pruebas: revisar antes de usar en producción.

INSERT INTO foods (name, category_id, is_prepared, default_unit_id) VALUES
    ('Aceite de algodón', 9, FALSE, 4),
    ('Aceite de cacahuete', 9, FALSE, 4),
    ('Aceite de coco', 9, FALSE, 4),
    ('Aceite de colza', 9, FALSE, 4),
    ('Aceite de germen de trigo', 9, FALSE, 4),
    ('Aceite de girasol', 9, FALSE, 4),
    ('Aceite de grano de uva', 9, FALSE, 4),
    ('Aceite de hígado de bacalao', 9, FALSE, 4),
    ('Aceite de lino', 9, FALSE, 4),
    ('Aceite de nuez', 9, FALSE, 4),
    ('Aceite de oliva', 9, FALSE, 4),
    ('Aceite de oliva virgen extra', 9, FALSE, 4),
    ('Aceite de oliva virgen extra, producción ecologica', 9, FALSE, 4),
    ('Aceite de palma', 9, FALSE, 4),
    ('Aceite de sésamo', 9, FALSE, 4),
    ('Aceite de soja', 9, FALSE, 4),
    ('Aceituna', 1, FALSE, 1),
    ('Aceituna negra, con hueso', 1, FALSE, 1),
    ('Acelga, cruda', 1, FALSE, 1),
    ('Acelga, en conserva', 10, FALSE, 1),
    ('Acelgas, hervidas', 1, FALSE, 1),
    ('Achicoria, cruda', 1, FALSE, 1),
    ('Agua de la red', 13, FALSE, 4),
    ('Agua mineral, mineralización debil', 13, FALSE, 4),
    ('Agua, con gas, embotellada', 13, FALSE, 4),
    ('Aguacate', 13, FALSE, 4),
    ('Aguacate congelado', 13, FALSE, 4),
    ('Aguardiente', 14, FALSE, 4),
    ('Ajo', 1, FALSE, 1),
    ('Ajo, en polvo', 9, FALSE, 1),
    ('Ajo, frito', 1, FALSE, 1),
    ('Albahaca', 9, FALSE, 1),
    ('Albaricoque', 1, FALSE, 1),
    ('Albondigas en conserva', 10, FALSE, 1),
    ('Alcachofa, cruda', 1, FALSE, 1),
    ('Alcachofas en conserva', 10, FALSE, 1),
    ('Alcaparra', 1, FALSE, 1),
    ('Alioli', 9, FALSE, 4),
    ('Almeja', 3, FALSE, 1),
    ('Almejas en conserva', 10, FALSE, 1),
    ('Almendra, cruda', 15, FALSE, 1),
    ('Almendra, cruda, con cáscara', 15, FALSE, 1),
    ('Almendra, frita, salada', 15, FALSE, 1),
    ('Almendra, tostada', 15, FALSE, 1),
    ('Almidón de arroz', 8, FALSE, 1),
    ('Almidón de maíz', 8, FALSE, 1),
    ('Almidón de trigo', 8, FALSE, 1),
    ('Altramuz', 8, FALSE, 1),
    ('Alubia blanca, en conserva', 10, FALSE, 1),
    ('Alubia blanca, seca, cruda', 8, FALSE, 1),
    ('Alubia negra, seca, remojada, hervida', 8, FALSE, 1),
    ('Anacardo, crudo', 15, FALSE, 1),
    ('Anchoas en aceite vegetal', 3, FALSE, 1),
    ('Anguila, al horno', 3, FALSE, 1),
    ('Anguila, cruda', 3, FALSE, 1),
    ('Anguila, hervida', 3, FALSE, 1),
    ('Angula, cruda', 3, FALSE, 1),
    ('Anís, seco', 14, FALSE, 4),
    ('Aperitivos de trigo', 7, FALSE, 1),
    ('Apio, crudo', 1, FALSE, 1),
    ('Apio, en conserva en salmuera', 10, FALSE, 1),
    ('Arandano', 1, FALSE, 1),
    ('Arenque, ahumado', 3, FALSE, 1),
    ('Arenque, salado', 3, FALSE, 1),
    ('Arroz', 8, FALSE, 1),
    ('Arroz con leche', 4, FALSE, 4),
    ('Arroz hinchado, para el desayuno, enriquecido', 8, FALSE, 1),
    ('Arroz integral, crudo', 8, FALSE, 1),
    ('Arroz integral, hervido', 8, FALSE, 1),
    ('Arroz, hervido', 8, FALSE, 1),
    ('Atún en aceite de oliva isabel', 3, FALSE, 1),
    ('Atun en aceite vegetal', 3, FALSE, 1),
    ('Atún en escabeche', 10, FALSE, 1),
    ('Atún, al horno', 3, FALSE, 1),
    ('Atún, al natural', 3, FALSE, 1),
    ('Atún, crudo', 3, FALSE, 1),
    ('Atún, plancha', 3, FALSE, 1),
    ('Avellana', 15, FALSE, 1),
    ('Avellana, cruda, con cáscara', 15, FALSE, 1),
    ('Avena, cruda', 7, FALSE, 1),
    ('Avestruz, solomillo, crudo', 2, FALSE, 1),
    ('Azafrán', 9, FALSE, 1),
    ('Azúcar blanca', 9, FALSE, 1),
    ('Azúcar, moreno', 9, FALSE, 1),
    ('Bacaladilla', 3, FALSE, 1),
    ('Bacalao, ahumado', 3, FALSE, 1),
    ('Bacalao, crudo', 3, FALSE, 1),
    ('Bacalao, fresco, al horno', 3, FALSE, 1),
    ('Bacalao, frito', 3, FALSE, 1),
    ('Bacalao, salado, crudo', 3, FALSE, 1),
    ('Bacalao, salado, remojado, crudo', 3, FALSE, 1),
    ('Bacón, ahumado, a la parrilla', 2, FALSE, 1),
    ('Bacon, crudo, con grasa separable', 2, FALSE, 1),
    ('Bambú, crudo', 1, FALSE, 1),
    ('Barra chocolate, tipo "bounty"', 15, FALSE, 1),
    ('Barra de chocolate, tipo "Kit-kat"', 15, FALSE, 1),
    ('Barra de chocolate, tipo "Mars"', 15, FALSE, 1),
    ('Barrita cereales con chocolate', 7, FALSE, 1),
    ('Barrita cereales con frutas', 7, FALSE, 1),
    ('Barrita cereales maíz y trigo', 7, FALSE, 1),
    ('Barrita cereales trigo y chocolate', 7, FALSE, 1),
    ('Batido de chocolate', 13, FALSE, 4),
    ('Batido de fresa', 13, FALSE, 4),
    ('Batido de soja', 13, FALSE, 4),
    ('Batido fermentado de soja', 9, FALSE, 1),
    ('Batido lácteo de cacao, bajo en calorías', 13, FALSE, 4),
    ('Batido lácteo, de fresa, bajo en calorías', 13, FALSE, 4),
    ('Bebida de soja', 13, FALSE, 4),
    ('Bebida energética', 13, FALSE, 4),
    ('Bebida isotónica', 13, FALSE, 4),
    ('Berberechos', 3, FALSE, 1),
    ('Berberechos en conserva', 10, FALSE, 1),
    ('Berenjena', 1, FALSE, 1),
    ('Berenjena, frita, en aceite de girasol', 1, FALSE, 1),
    ('Berro, crudo', 1, FALSE, 1),
    ('Besugo', 3, FALSE, 1),
    ('Bígaro, hervido', 3, FALSE, 1),
    ('Bizcocho', 6, FALSE, 1),
    ('Bocadillo', 11, TRUE, 1),
    ('Bogavante', 3, FALSE, 1),
    ('Bogavante, hervido', 3, FALSE, 1),
    ('Bollería, genérico', 6, FALSE, 1),
    ('Bombón', 15, FALSE, 1),
    ('Boniato, crudo', 1, FALSE, 1),
    ('Bonito del norte, al vapor', 3, FALSE, 1),
    ('Bonito del norte, enlatado en aceite de soja', 10, FALSE, 1),
    ('Bonito en aceite vegetal', 3, FALSE, 1),
    ('Bonito, enlatado en aceite, escurrido', 10, FALSE, 1),
    ('Boquerón', 3, FALSE, 1),
    ('Boquerón, frito', 3, FALSE, 1),
    ('Borraja', 1, FALSE, 1),
    ('Breca, cruda', 3, FALSE, 1),
    ('Brécol, crudo', 1, FALSE, 1),
    ('Brécol, hervido', 1, FALSE, 1),
    ('Butifarra', 2, FALSE, 1),
    ('Caballa, al horno', 3, FALSE, 1),
    ('Caballa, cruda', 3, FALSE, 1),
    ('Caballa, enlatada en aceite, escurrida', 10, FALSE, 1),
    ('Cabracho o rascacio, crudo', 3, FALSE, 1),
    ('Cabrito lechal, costillar, asado', 2, FALSE, 1),
    ('Cabrito lechal, costillar, crudo', 2, FALSE, 1),
    ('Cabrito lechal, espalda, cruda', 2, FALSE, 1),
    ('Cabrito lechal, pierna, cruda', 2, FALSE, 1),
    ('Cabrito, parte s/e, crudo, con grasa separable', 2, FALSE, 1),
    ('Cacahuete, crudo, con cáscara', 15, FALSE, 1),
    ('Cacahuete, frito, salado', 15, FALSE, 1),
    ('Cacahuete, tostado, salado', 15, FALSE, 1),
    ('Cacao en polvo, azucarado', 9, FALSE, 1),
    ('Cacao, en polvo, azucarado, bajo en calorías', 9, FALSE, 1),
    ('Café, con leche', 13, FALSE, 4),
    ('Café, en grano o molido, descafeinado', 13, FALSE, 4),
    ('Café, en polvo, sin reconstituir', 13, FALSE, 4),
    ('Café, en polvo, soluble', 13, FALSE, 4),
    ('Café, infusión', 13, FALSE, 4),
    ('Café, infusión, descafeinado', 13, FALSE, 4),
    ('Café, sucedáneo, soluble', 13, FALSE, 4),
    ('Calabacín', 1, FALSE, 1),
    ('Calabacín, asado', 1, FALSE, 1),
    ('Calabaza, cruda', 1, FALSE, 1),
    ('Calabaza, hervida', 1, FALSE, 1),
    ('Calamar, asado', 3, FALSE, 1),
    ('Calamar, conserva', 10, FALSE, 1),
    ('Calamar, crudo', 3, FALSE, 1),
    ('Calamares en aceite vegetal', 3, FALSE, 1),
    ('Caldo vegetal', 9, FALSE, 1),
    ('Callos de ternera', 2, FALSE, 1),
    ('Camarón', 3, FALSE, 1),
    ('Canela, en polvo', 9, FALSE, 1),
    ('Canelones', 11, TRUE, 1),
    ('Cangrejo', 3, FALSE, 1),
    ('Cangrejo de río crudo', 3, FALSE, 1),
    ('Cangrejo, en conserva', 10, FALSE, 1),
    ('Canonigos', 1, FALSE, 1),
    ('Caqui', 1, FALSE, 1),
    ('Caracol', 2, FALSE, 1),
    ('Caramelo', 15, FALSE, 1),
    ('Cardo', 1, FALSE, 1),
    ('Cardo, tallo, en conserva', 10, FALSE, 1),
    ('Carne de cerdo de capa blanca, cabezada, parte magra, cruda', 2, FALSE, 1),
    ('Carne de cerdo de capa blanca, cabezada, partes grasa y magra, crudo', 2, FALSE, 1),
    ('Carne de cerdo de capa blanca, chuleta, parte magra, cruda', 2, FALSE, 1),
    ('Carne de cerdo de capa blanca, chuleta, partes grasa y magra, cruda', 2, FALSE, 1),
    ('Carne de cerdo de capa blanca, jamón, parte magra, crudo', 2, FALSE, 1),
    ('Carne de cerdo de capa blanca, jamón, partes grasa y magra, crudo', 2, FALSE, 1),
    ('Carne de cerdo de capa blanca, lomo, parte magra, crudo', 2, FALSE, 1),
    ('Carne de cerdo de capa blanca, lomo, partes grasa y magra, crudo', 2, FALSE, 1),
    ('Carne de vacuno, cadera, partes magra y grasa, crudo', 2, FALSE, 1),
    ('Carne de vacuno, carrillera, partes magra y grasa, crudo', 2, FALSE, 1),
    ('Carne de vacuno, costillar, partes magra y grasa, crudo', 2, FALSE, 1),
    ('Carne de vacuno, lomo, partes magra y grasa, crudo', 2, FALSE, 1),
    ('Carne de vacuno, rabo, partes magra y grasa, crudo', 2, FALSE, 1),
    ('Carne de vacuno, redondo, partes magra y grasa, crudo', 2, FALSE, 1),
    ('Carne de vacuno, solomillo, partes magra y grasa, crudo', 2, FALSE, 1),
    ('Carne picada', 2, FALSE, 1),
    ('Carpa, al horno', 3, FALSE, 1),
    ('Carpa, cruda', 3, FALSE, 1),
    ('Castaña, cruda', 15, FALSE, 1),
    ('Castaña, tostada', 15, FALSE, 1),
    ('Cava', 14, FALSE, 4),
    ('Caviar', 3, FALSE, 1),
    ('Cebada, cruda', 7, FALSE, 1),
    ('Cebolla', 1, FALSE, 1),
    ('Cebolla, asada', 1, FALSE, 1),
    ('Cebolla, hervida', 1, FALSE, 1),
    ('Cebollino, crudo', 1, FALSE, 1),
    ('Cecina', 2, FALSE, 1),
    ('Centeno, crudo', 7, FALSE, 1),
    ('Centollo, crudo', 3, FALSE, 1),
    ('Cerdo, chuleta, crudo', 2, FALSE, 1),
    ('Cerdo, costilla, crudo', 2, FALSE, 1),
    ('Cerdo, lomo, asado', 2, FALSE, 1),
    ('Cerdo, lomo, crudo', 2, FALSE, 1),
    ('Cerdo, panceta, cruda', 2, FALSE, 1),
    ('Cerdo, parte sin especificar', 2, FALSE, 1),
    ('Cerdo, pierna, cruda, con grasa separable', 2, FALSE, 1),
    ('Cerdo, solomillo, asado', 2, FALSE, 1),
    ('Cerdo, solomillo, crudo', 2, FALSE, 1),
    ('Cereales base trigo y chocolate', 7, FALSE, 1),
    ('Cereales desayuno base de arroz chocolateado', 8, FALSE, 1),
    ('Cereales desayuno base de arroz y miel', 9, FALSE, 1),
    ('Cereales desayuno base de arroz, trigo y fruta', 8, FALSE, 1),
    ('Cereales desayuno base de maíz y miel', 9, FALSE, 1),
    ('Cereales desayuno base de maíz y trigo', 7, FALSE, 1),
    ('Cereales desayuno base de maíz, trigo y avena', 7, FALSE, 1),
    ('Cereales desayuno base de trigo azucarado', 9, FALSE, 1),
    ('Cereales desayuno base de trigo y arroz', 8, FALSE, 1),
    ('Cereales desayuno base de trigo y frutas', 7, FALSE, 1),
    ('Cereales desayuno base de trigo y miel', 9, FALSE, 1),
    ('Cereales desayuno base de trigo, avena, maiz y miel', 9, FALSE, 1),
    ('Cereales desayuno base de trigo, avena, maíz, miel y nueces', 9, FALSE, 1),
    ('Cereales desayuno base muesli', 7, FALSE, 1),
    ('Cereales desayuno, maíz azucarado', 9, FALSE, 1),
    ('Cereales para el desayuno, ricos en fibra, tipo "all-bran"', 7, FALSE, 1),
    ('Cereales, en polvo, solubles (eko)', 7, FALSE, 1),
    ('Cereza', 1, FALSE, 1),
    ('Cerveza con alcohol', 14, FALSE, 4),
    ('Cerveza sin alcohol', 14, FALSE, 4),
    ('Cerveza, baja en alcohol', 14, FALSE, 4),
    ('Cerveza, oscura, 8°- 9°', 14, FALSE, 4),
    ('Champiñon', 15, FALSE, 1),
    ('Champiñones en conserva', 15, FALSE, 1),
    ('Chayote, crudo', 1, FALSE, 1),
    ('Chicle, sin azúcar', 9, FALSE, 1),
    ('Chile, rojo', 1, FALSE, 1),
    ('Chile, verde', 1, FALSE, 1),
    ('Chipiron', 3, FALSE, 1),
    ('Chirimoya', 1, FALSE, 1),
    ('Chirla', 3, FALSE, 1),
    ('Chistorra', 2, FALSE, 1),
    ('Chocolate blanco', 15, FALSE, 1),
    ('Chocolate con leche', 4, FALSE, 4),
    ('Chocolate con leche y almendras', 4, FALSE, 4),
    ('Chocolate con leche y arroz', 4, FALSE, 4),
    ('Chocolate con nueces de macadamia', 15, FALSE, 1),
    ('Chocolate negro, con almendras', 15, FALSE, 1),
    ('Chocolate negro, con azúcar', 9, FALSE, 1),
    ('Chocolate, negro', 15, FALSE, 1),
    ('Choped pork', 2, FALSE, 1),
    ('Chorizo', 2, FALSE, 1),
    ('Chufa, cruda', 15, FALSE, 1),
    ('Churro', 6, FALSE, 1),
    ('Ciervo, parte s/e, crudo, con grasa separable', 2, FALSE, 1),
    ('Cigala', 3, FALSE, 1),
    ('Ciruela, con piel, cruda', 1, FALSE, 1),
    ('Ciruela, sin piel', 1, FALSE, 1),
    ('Coco, desecado', 1, FALSE, 1),
    ('Coco, fresco', 1, FALSE, 1),
    ('Col blanca, cruda', 1, FALSE, 1),
    ('Col de bruselas, cruda', 1, FALSE, 1),
    ('Col lombarda, hervida', 1, FALSE, 1),
    ('Col rizada, cruda', 1, FALSE, 1),
    ('Coliflor, congelada, cruda', 1, FALSE, 1),
    ('Coliflor, hervida', 1, FALSE, 1),
    ('Comino', 9, FALSE, 1),
    ('Complejo vitaminico', 16, FALSE, 1),
    ('Coñac', 14, FALSE, 4),
    ('Conejo de granja, carne, cruda', 2, FALSE, 1),
    ('Conejo, entero, estofado', 2, FALSE, 1),
    ('Confitura, frutas s/e, baja en calorías', 9, FALSE, 1),
    ('Congrio', 3, FALSE, 1),
    ('Corazón de cordero, crudo', 2, FALSE, 1),
    ('Corazón de pollo, crudo', 2, FALSE, 1),
    ('Corazon de vaca, crudo', 2, FALSE, 1),
    ('Corazón, de cerdo, crudo', 2, FALSE, 1),
    ('Corazón, de vaca/buey, cocido', 2, FALSE, 1),
    ('Corazón, de vaca/buey, crudo', 2, FALSE, 1),
    ('Cordero lechal, costillar, asado', 2, FALSE, 1),
    ('Cordero lechal, costillar, crudo', 2, FALSE, 1),
    ('Cordero lechal, espalda, cruda', 2, FALSE, 1),
    ('Cordero lechal, pierna, cruda', 2, FALSE, 1),
    ('Cordero ligero, costillar, asado', 2, FALSE, 1),
    ('Cordero ligero, costillar, crudo', 2, FALSE, 1),
    ('Cordero ligero, espalda, cruda', 2, FALSE, 1),
    ('Cordero ligero, pierna, cruda', 2, FALSE, 1),
    ('Cordero, costilla, crudo', 2, FALSE, 1),
    ('Cordero, parte sin especificar', 2, FALSE, 1),
    ('Cordero, pierna, con grasa, asada', 2, FALSE, 1),
    ('Corteza de trigo', 7, FALSE, 1),
    ('Crema catalana', 11, TRUE, 1),
    ('Crema de almendras', 15, FALSE, 1),
    ('Crema de cacahuete', 15, FALSE, 1),
    ('Crema de chocolate con avellanas', 15, FALSE, 1),
    ('Crema de chocolate y nata', 4, FALSE, 1),
    ('Crema de chocolate, baja en calorías', 15, FALSE, 1),
    ('Crema de coco', 1, FALSE, 1),
    ('Crema de vainilla y mousse de chocolate', 9, FALSE, 1),
    ('Crema inglesa', 11, TRUE, 1),
    ('Crema pastelera', 11, TRUE, 1),
    ('Cremoso san millan', 16, FALSE, 1),
    ('Croissant', 6, FALSE, 1),
    ('Croissant de chocolate', 6, FALSE, 1),
    ('Croquetas de pollo', 11, TRUE, 1),
    ('Cuajada', 4, FALSE, 1),
    ('Cubata', 14, FALSE, 4),
    ('Cubito de caldo', 9, FALSE, 1),
    ('Curry', 9, FALSE, 1),
    ('Dátil', 1, FALSE, 1),
    ('Donut', 6, FALSE, 1),
    ('Donut, de chocolate', 6, FALSE, 1),
    ('Dorada, cruda', 3, FALSE, 1),
    ('Dorada, plancha', 3, FALSE, 1),
    ('Empanada de carne', 11, TRUE, 1),
    ('Empanadilla', 11, TRUE, 1),
    ('Endibia', 1, FALSE, 1),
    ('Eneldo, seco', 9, FALSE, 1),
    ('Ensaimada', 6, FALSE, 1),
    ('Ensalada', 1, FALSE, 1),
    ('Ensaladilla rusa', 11, TRUE, 1),
    ('Escarola', 1, FALSE, 1),
    ('Espárrago, verde', 1, FALSE, 1),
    ('Esparragos blancos en conserva', 10, FALSE, 1),
    ('Espinaca, en conserva', 10, FALSE, 1),
    ('Espinaca, hervida', 1, FALSE, 1),
    ('Espinaca, picada, congelada, cruda', 1, FALSE, 1),
    ('Fabada', 11, TRUE, 1),
    ('Faneca, cruda', 3, FALSE, 1),
    ('Flamenquín', 11, TRUE, 1),
    ('Flan de huevo', 5, FALSE, 7),
    ('Flan de huevo, bajo en calorías', 5, FALSE, 7),
    ('Fletan, crudo', 3, FALSE, 1),
    ('Foie gras', 2, FALSE, 1),
    ('Frambuesa, cruda', 1, FALSE, 1),
    ('Fresa', 1, FALSE, 1),
    ('Fritos de maíz', 15, FALSE, 1),
    ('Fructosa', 9, FALSE, 1),
    ('Frutos secos', 15, FALSE, 1),
    ('Fuet', 2, FALSE, 1),
    ('Galleta ,tipo "digestiva", con chocolate', 15, FALSE, 1),
    ('Galleta salada', 15, FALSE, 1),
    ('Galleta, barquillo, con jalea de frutas', 15, FALSE, 1),
    ('Galleta, cubierta de chocolate', 15, FALSE, 1),
    ('Galleta, genérico', 15, FALSE, 1),
    ('Galleta, tipo "Digestiva"', 15, FALSE, 1),
    ('Galletas integrales', 15, FALSE, 1),
    ('Galletas saladas, con queso', 4, FALSE, 1),
    ('Galletas tipo maria', 15, FALSE, 1),
    ('Galletas, con chocolate, tipo "cookies"', 15, FALSE, 1),
    ('Galletas, de mantequilla', 4, FALSE, 1),
    ('Gallina, entera, cruda', 2, FALSE, 1),
    ('Gallo', 3, FALSE, 1),
    ('Gamba quisquilla, congelada', 3, FALSE, 1),
    ('Gamba roja, cruda', 3, FALSE, 1),
    ('Gamba, hervida', 3, FALSE, 1),
    ('Garbanzo, en conserva', 10, FALSE, 1),
    ('Garbanzo, hervido', 8, FALSE, 1),
    ('Garbanzo, seco, crudo', 8, FALSE, 1),
    ('Gazpacho', 11, TRUE, 1),
    ('Gelatina', 16, FALSE, 1),
    ('Germen de trigo', 7, FALSE, 1),
    ('Ginebra', 14, FALSE, 4),
    ('Gofio', 7, FALSE, 1),
    ('Gomasio', 9, FALSE, 1),
    ('Gominola, genérica', 15, FALSE, 1),
    ('Granada', 1, FALSE, 1),
    ('Grasa de pollo', 2, FALSE, 1),
    ('Grelo', 1, FALSE, 1),
    ('Grosella negra, cruda', 1, FALSE, 1),
    ('Grosella, cruda', 1, FALSE, 1),
    ('Guayaba, enlatada en almíbar', 10, FALSE, 1),
    ('Guayaba, sin piel, cruda', 1, FALSE, 1),
    ('Guindilla, en polvo', 9, FALSE, 1),
    ('Guindilla, picante', 9, FALSE, 1),
    ('Guisante, congelado, crudo', 1, FALSE, 1),
    ('Guisante, congelado, hervido', 1, FALSE, 1),
    ('Guisante, seco, crudo', 1, FALSE, 1),
    ('Guisantes en conserva', 10, FALSE, 1),
    ('Gusanito', 15, FALSE, 1),
    ('Haba, fresca', 8, FALSE, 1),
    ('Haba, frita', 8, FALSE, 1),
    ('Haba, seca', 8, FALSE, 1),
    ('Haba, seca, remojada, hervida', 8, FALSE, 1),
    ('Harina de avena', 7, FALSE, 1),
    ('Harina de avena, cocida en agua', 13, FALSE, 4),
    ('Harina de cebada', 7, FALSE, 1),
    ('Harina de centeno', 7, FALSE, 1),
    ('Harina de maíz', 7, FALSE, 1),
    ('Harina de soja', 8, FALSE, 1),
    ('Harina de trigo', 7, FALSE, 1),
    ('Harina de trigo, integral', 7, FALSE, 1),
    ('Helado de chocolate', 15, FALSE, 1),
    ('Helado de fresa', 1, FALSE, 1),
    ('Helado de nata', 4, FALSE, 1),
    ('Higado de pollo, crudo', 2, FALSE, 1),
    ('Hígado, de cerdo, crudo', 2, FALSE, 1),
    ('Hígado, de vaca/buey, crudo', 2, FALSE, 1),
    ('Higos y brevas', 1, FALSE, 1),
    ('Hinojo', 9, FALSE, 1),
    ('Hojaldre', 6, FALSE, 1),
    ('Horchata', 13, FALSE, 4),
    ('Huevo de codorniz, entero, crudo', 5, FALSE, 7),
    ('Huevo de gallina fresco', 5, FALSE, 7),
    ('Huevo de gallina, clara, cruda', 5, FALSE, 7),
    ('Huevo de gallina, escalfado', 5, FALSE, 7),
    ('Huevo de gallina, frito', 5, FALSE, 7),
    ('Huevo de gallina, hervido, duro', 5, FALSE, 7),
    ('Huevo de gallina, pasado por agua', 13, FALSE, 4),
    ('Huevo de gallina, revuelto, con mantequilla', 5, FALSE, 7),
    ('Huevo de gallina, yema, cruda', 5, FALSE, 7),
    ('Huevo de gallina, yema, desecada', 5, FALSE, 7),
    ('Huevo de pato, crudo', 5, FALSE, 7),
    ('Huevo de pavo, entero, crudo', 5, FALSE, 7),
    ('Infusión', 13, FALSE, 4),
    ('Jalea real', 16, FALSE, 1),
    ('Jamón asado', 2, FALSE, 1),
    ('Jamón cocido, categoría s/e', 2, FALSE, 1),
    ('Jamón cocido, enlatado', 10, FALSE, 1),
    ('Jamón ibérico de bellota', 2, FALSE, 1),
    ('Jamón ibérico de cebo', 2, FALSE, 1),
    ('Jamón serrano', 2, FALSE, 1),
    ('Jengibre', 9, FALSE, 1),
    ('Judía blanca', 8, FALSE, 1),
    ('Judía pinta', 8, FALSE, 1),
    ('Judía verde, congelada, cruda', 8, FALSE, 1),
    ('Judía verde, cruda', 8, FALSE, 1),
    ('Judia verde, hervida', 8, FALSE, 1),
    ('Judías blancas, cocidas', 8, FALSE, 1),
    ('Judias verdes en conserva', 10, FALSE, 1),
    ('Jurel, crudo', 3, FALSE, 1),
    ('Kebab', 11, TRUE, 1),
    ('Kefir', 4, FALSE, 1),
    ('Ketchup', 9, FALSE, 1),
    ('Kiwi', 1, FALSE, 1),
    ('Lacón', 2, FALSE, 1),
    ('Lactosa', 9, FALSE, 1),
    ('Langosta', 3, FALSE, 1),
    ('Langostino', 3, FALSE, 1),
    ('Lasaña', 11, TRUE, 1),
    ('Laurel, hoja', 9, FALSE, 1),
    ('Leche condensada, entera, con azúcar', 9, FALSE, 1),
    ('Leche de almendra', 4, FALSE, 4),
    ('Leche de cabra', 4, FALSE, 4),
    ('Leche de coco', 4, FALSE, 4),
    ('Leche de oveja', 4, FALSE, 4),
    ('Leche de vaca, desnatada, condensada, con azúcar', 9, FALSE, 1),
    ('Leche de vaca, entera', 4, FALSE, 4),
    ('Leche en polvo, semidesnatada', 4, FALSE, 4),
    ('Leche fermentada, bifidobacterium, entera, natural', 9, FALSE, 1),
    ('Leche materna', 4, FALSE, 4),
    ('Leche merengada', 4, FALSE, 4),
    ('Leche, desnatada, pasteurizada', 4, FALSE, 4),
    ('Leche, semidesnatada, pasteurizada', 4, FALSE, 4),
    ('Lechuga', 1, FALSE, 1),
    ('Lecitina de soja', 8, FALSE, 1),
    ('Lengua de cerdo, cruda', 2, FALSE, 1),
    ('Lengua de cordero, cruda', 2, FALSE, 1),
    ('Lengua, de buey, cruda', 2, FALSE, 1),
    ('Lengua, de ternera, cruda', 2, FALSE, 1),
    ('Lenguado', 3, FALSE, 1),
    ('Lenguado, al horno', 3, FALSE, 1),
    ('Lenguado, frito', 3, FALSE, 1),
    ('Lenguado, plancha', 3, FALSE, 1),
    ('Lenteja, en conserva', 10, FALSE, 1),
    ('Lenteja, hervida', 8, FALSE, 1),
    ('Lenteja, seca, cruda', 8, FALSE, 1),
    ('Licor apricot', 14, FALSE, 4),
    ('Licor benedictine', 14, FALSE, 4),
    ('Licor curaçao', 14, FALSE, 4),
    ('Licor de café', 14, FALSE, 4),
    ('Licor de crema 15-17% vol.', 14, FALSE, 4),
    ('Licores de frutas', 14, FALSE, 4),
    ('Liebre, entera, cruda', 2, FALSE, 1),
    ('Lija, cruda', 3, FALSE, 1),
    ('Lima, cruda', 1, FALSE, 1),
    ('Limonada', 13, FALSE, 4),
    ('Litchi, crudo', 1, FALSE, 1),
    ('Lombarda', 1, FALSE, 1),
    ('Lomo embuchado', 2, FALSE, 1),
    ('Longaniza', 2, FALSE, 1),
    ('Lubina', 3, FALSE, 1),
    ('Lucio, al horno', 3, FALSE, 1),
    ('Macedonia de frutas, conserva en su jugo', 10, FALSE, 1),
    ('Magdalena', 6, FALSE, 1),
    ('Maíz, en mazorca, congelado, crudo', 7, FALSE, 1),
    ('Maíz, en mazorca, crudo', 7, FALSE, 1),
    ('Mandarina', 1, FALSE, 1),
    ('Mandarina, congelada', 1, FALSE, 1),
    ('Mango, crudo', 1, FALSE, 1),
    ('Manteca', 9, FALSE, 1),
    ('Mantequilla salada', 4, FALSE, 1),
    ('Mantequilla, baja en calorías', 4, FALSE, 1),
    ('Manzana', 1, FALSE, 1),
    ('Margarina de maíz', 9, FALSE, 1),
    ('Margarina, baja en calorías', 9, FALSE, 1),
    ('Masa de hojaldre, cruda', 6, FALSE, 1),
    ('Mayonesa con aceite de girasol', 9, FALSE, 4),
    ('Mayonesa, aceite de oliva', 9, FALSE, 4),
    ('Mayonesa, aceite de soja', 9, FALSE, 4),
    ('Mayonesa, baja en calorías', 9, FALSE, 4),
    ('Mejillon', 3, FALSE, 1),
    ('Mejillón, en conserva, al natural', 10, FALSE, 1),
    ('Mejillón, en escabeche', 10, FALSE, 1),
    ('Mejillón, hervido', 3, FALSE, 1),
    ('Melocotón', 1, FALSE, 1),
    ('Melocotón en almíbar', 10, FALSE, 1),
    ('Melocotón, desecado', 1, FALSE, 1),
    ('Melón', 1, FALSE, 1),
    ('Membrillo, crudo', 1, FALSE, 1),
    ('Menestra de verduras, congelada', 11, TRUE, 1),
    ('Menta, fresca', 9, FALSE, 1),
    ('Merluza fresca', 3, FALSE, 1),
    ('Merluza, congelada, cruda', 3, FALSE, 1),
    ('Merluza, rebozada, frita', 3, FALSE, 1),
    ('Mermelada de albaricoque', 9, FALSE, 1),
    ('Mermelada de albaricoque y melocotón, baja en calorías', 9, FALSE, 1),
    ('Mermelada de ciruela', 9, FALSE, 1),
    ('Mermelada de frambuesa', 9, FALSE, 1),
    ('Mermelada de fresa', 9, FALSE, 1),
    ('Mermelada de fresa, baja en calorías', 9, FALSE, 1),
    ('Mermelada de grosella roja', 9, FALSE, 1),
    ('Mermelada de mora', 9, FALSE, 1),
    ('Mermelada de naranja', 9, FALSE, 1),
    ('Mero, crudo', 3, FALSE, 1),
    ('Mero, plancha', 3, FALSE, 1),
    ('Miel', 9, FALSE, 1),
    ('Mijo', 7, FALSE, 1),
    ('Miso', 9, FALSE, 1),
    ('Mojo picon', 9, FALSE, 1),
    ('Molleja de cordero', 2, FALSE, 1),
    ('Morcilla', 2, FALSE, 1),
    ('Morcilla, frita', 2, FALSE, 1),
    ('Mortadela', 2, FALSE, 1),
    ('Mostaza', 9, FALSE, 1),
    ('Mousse de chocolate', 15, FALSE, 1),
    ('Mousse de queso fresco, con frutas', 4, FALSE, 1),
    ('Mousse de queso fresco, desnatado, azucarado', 9, FALSE, 1),
    ('Mousse de queso fresco, desnatado, con frutas', 4, FALSE, 1),
    ('Mousse de yogur, con frutas', 4, FALSE, 1),
    ('Mousse de yogur, natural', 4, FALSE, 1),
    ('Muesli', 7, FALSE, 1),
    ('Mújol, al horno', 3, FALSE, 1),
    ('Mújol, crudo', 3, FALSE, 1),
    ('Nabo, pelado, crudo', 1, FALSE, 1),
    ('Napolitana, rellena con crema de cacao', 7, FALSE, 1),
    ('Naranja', 1, FALSE, 1),
    ('Nata montada', 4, FALSE, 1),
    ('Nata, líquida, para cocinar, 18% de grasa', 4, FALSE, 1),
    ('Natillas sabor vainilla', 9, FALSE, 1),
    ('Nécora', 3, FALSE, 1),
    ('Néctar de albaricoque, envasado', 13, FALSE, 4),
    ('Néctar de ciruela', 13, FALSE, 4),
    ('Néctar de frutas exóticas, envasado', 13, FALSE, 4),
    ('Néctar de mango, envasado', 13, FALSE, 4),
    ('Néctar de maracuyá, envasado', 13, FALSE, 4),
    ('Néctar de melocotón', 13, FALSE, 4),
    ('Néctar de naranja, envasado', 13, FALSE, 4),
    ('Néctar de pera, envasado', 13, FALSE, 4),
    ('Néctar de piña', 13, FALSE, 4),
    ('Néctar de pomelo', 13, FALSE, 4),
    ('Nectarina', 13, FALSE, 4),
    ('Níscalo, crudo', 1, FALSE, 1),
    ('Níspero, con piel, crudo', 1, FALSE, 1),
    ('Nispero, conserva en su jugo', 10, FALSE, 1),
    ('Nispero, sin piel , congelado', 1, FALSE, 1),
    ('Nuez', 15, FALSE, 1),
    ('Nuez moscada', 9, FALSE, 1),
    ('Nuez, cruda, con cáscara', 15, FALSE, 1),
    ('Oca, sin piel, asada', 2, FALSE, 1),
    ('Orégano, seco', 9, FALSE, 1),
    ('Ostra, cruda', 3, FALSE, 1),
    ('Paella', 11, TRUE, 1),
    ('Paella marinera', 11, TRUE, 1),
    ('Palmera', 6, FALSE, 1),
    ('Palmito, en conserva', 10, FALSE, 1),
    ('Palometa, cruda', 3, FALSE, 1),
    ('Palomitas de maíz, sin aceite, sin sal', 15, FALSE, 1),
    ('Pan blanco, de barra', 6, FALSE, 1),
    ('Pan blanco, de barra, sin sal', 6, FALSE, 1),
    ('Pan blanco, de molde, tostado', 6, FALSE, 1),
    ('Pan blanco, frito', 6, FALSE, 1),
    ('Pan blanco, tipo "baguette"', 6, FALSE, 1),
    ('Pan blanco, tostado', 6, FALSE, 1),
    ('Pan blanco, tostado sin sal', 6, FALSE, 1),
    ('Pan de avena', 7, FALSE, 1),
    ('Pan de cebada', 7, FALSE, 1),
    ('Pan de centeno', 7, FALSE, 1),
    ('Pan de leche', 4, FALSE, 4),
    ('Pan de maíz', 6, FALSE, 1),
    ('Pan integral', 6, FALSE, 1),
    ('Pan integral, de molde, tostado', 6, FALSE, 1),
    ('Pan integral, sin sal', 6, FALSE, 1),
    ('Pan integral, tostado', 6, FALSE, 1),
    ('Pan rallado', 6, FALSE, 1),
    ('Pan tostado integral', 6, FALSE, 1),
    ('Pan, tipo hamburguesa', 6, FALSE, 1),
    ('Panceta, frita', 6, FALSE, 1),
    ('Panga, cruda', 6, FALSE, 1),
    ('Papaya, cruda', 1, FALSE, 1),
    ('Paraguaya', 13, FALSE, 4),
    ('Pasta alimenticia, con huevo, cruda', 5, FALSE, 7),
    ('Pasta alimenticia, con huevo, hervida', 5, FALSE, 7),
    ('Pasta alimenticia, con vegetales, cruda', 8, FALSE, 1),
    ('Pasta alimenticia, cruda', 8, FALSE, 1),
    ('Pasta alimenticia, integral, cruda', 8, FALSE, 1),
    ('Pasta alimenticia, integral, hervida', 8, FALSE, 1),
    ('Pasta alimenticia, rellena con carne, hervida', 8, FALSE, 1),
    ('Pasta de fruta', 15, FALSE, 1),
    ('Pasta de sésamo', 15, FALSE, 1),
    ('Pastas de te', 6, FALSE, 1),
    ('Pastel', 6, FALSE, 1),
    ('Pastel con fruta confitada', 6, FALSE, 1),
    ('Pastel de chocolate', 6, FALSE, 1),
    ('Pastel de manzana', 6, FALSE, 1),
    ('Patata, asada', 1, FALSE, 1),
    ('Patata, cruda', 1, FALSE, 1),
    ('Patata, frita con aceite s/e, sin sal', 1, FALSE, 1),
    ('Patata, hervida', 1, FALSE, 1),
    ('Patata, prefrita, congelada', 1, FALSE, 1),
    ('Patata, salteada con aceite girasol', 1, FALSE, 1),
    ('Patatas chips, "lights"', 15, FALSE, 1),
    ('Patatas, fritas, chips', 15, FALSE, 1),
    ('Pate de higado de cerdo, 30% de grasa', 2, FALSE, 1),
    ('Paté de pimienta', 9, FALSE, 1),
    ('Pato, entero, asado', 2, FALSE, 1),
    ('Pato, entero, crudo', 2, FALSE, 1),
    ('Pavo, crudo', 2, FALSE, 1),
    ('Pavo, fiambre', 2, FALSE, 1),
    ('Pavo, fiambre, bajo en grasa', 2, FALSE, 1),
    ('Pavo, muslo, con piel, crudo', 2, FALSE, 1),
    ('Pavo, pechuga, con piel, crudo', 2, FALSE, 1),
    ('Pavo, pechuga, sin piel, a la plancha', 2, FALSE, 1),
    ('Pepinillos en vinagre', 1, FALSE, 1),
    ('Pepino', 1, FALSE, 1),
    ('Pera', 1, FALSE, 1),
    ('Pera, enlatada en almíbar', 10, FALSE, 1),
    ('Perca, al horno', 3, FALSE, 1),
    ('Perca, cruda', 3, FALSE, 1),
    ('Percebe', 3, FALSE, 1),
    ('Perdiz, cruda', 2, FALSE, 1),
    ('Perejil, fresco', 9, FALSE, 1),
    ('Pescadilla, congelada, cruda', 3, FALSE, 1),
    ('Pescadilla, rebozada en harina, frita', 7, FALSE, 1),
    ('Pescado, genérico', 3, FALSE, 1),
    ('Petit líquido, sabor fresa', 4, FALSE, 4),
    ('Petit suïsse, cereales y fruta', 4, FALSE, 1),
    ('Petit suisse, chocolate', 4, FALSE, 1),
    ('Petit suisse, fresa', 4, FALSE, 1),
    ('Petit Suisse, natural azucarado', 9, FALSE, 1),
    ('Pez espada, crudo', 3, FALSE, 1),
    ('Pez espada, emperador, plancha', 3, FALSE, 1),
    ('Pichón, sin piel, asado', 2, FALSE, 1),
    ('Pijota, cruda', 3, FALSE, 1),
    ('Pimentón, en polvo', 9, FALSE, 1),
    ('Pimienta, blanca', 9, FALSE, 1),
    ('Pimienta, negra', 9, FALSE, 1),
    ('Pimiento morrón, en conserva', 10, FALSE, 1),
    ('Pimiento rojo, crudo', 1, FALSE, 1),
    ('Pimiento, frito', 1, FALSE, 1),
    ('Piña', 1, FALSE, 1),
    ('Piña en almíbar', 10, FALSE, 1),
    ('Piña, enlatada en su jugo', 10, FALSE, 1),
    ('Piñon', 15, FALSE, 1),
    ('Piñón, crudo, con cáscara', 15, FALSE, 1),
    ('Pipa de calabaza', 15, FALSE, 1),
    ('Pipa de girasol', 15, FALSE, 1),
    ('Pipas de girasol, peladas, con sal', 15, FALSE, 1),
    ('Pistacho', 15, FALSE, 1),
    ('Pistacho deshidratado suave', 15, FALSE, 1),
    ('Pizza, precocinada', 11, TRUE, 1),
    ('Plátano', 1, FALSE, 1),
    ('Platija, al vapor', 3, FALSE, 1),
    ('Platija, cruda', 3, FALSE, 1),
    ('Pollo empanado, frito', 2, FALSE, 1),
    ('Pollo, ala, con piel, cruda', 2, FALSE, 1),
    ('Pollo, entero, con piel, asado', 2, FALSE, 1),
    ('Pollo, entero, con piel, crudo', 2, FALSE, 1),
    ('Pollo, fiambre', 2, FALSE, 1),
    ('Pollo, fiambre, bajo en grasa', 2, FALSE, 1),
    ('Pollo, frito', 2, FALSE, 1),
    ('Pollo, muslo, con piel, asado', 2, FALSE, 1),
    ('Pollo, muslo, con piel, crudo', 2, FALSE, 1),
    ('Pollo, parte sin especificar', 2, FALSE, 1),
    ('Pollo, pechuga, con piel, crudo', 2, FALSE, 1),
    ('Pollo, pechuga, plancha', 2, FALSE, 1),
    ('Pomelo', 1, FALSE, 1),
    ('Preparado lácteo con omega 3', 16, FALSE, 1),
    ('Pudding de pasas', 11, TRUE, 1),
    ('Puerro, crudo y congelado', 1, FALSE, 1),
    ('Puerro, en conserva', 10, FALSE, 1),
    ('Pulmón, de cerdo, crudo', 2, FALSE, 1),
    ('Pulmón, de cordero, crudo', 2, FALSE, 1),
    ('Pulmón, de ternera, crudo', 2, FALSE, 1),
    ('Pulpo', 3, FALSE, 1),
    ('Pulpo, hervido', 3, FALSE, 1),
    ('Puré de patata y queso, en copos', 4, FALSE, 1),
    ('Puré de patata, con verduras, en copos', 11, TRUE, 1),
    ('Puré de patata, en copos', 11, TRUE, 1),
    ('Puré de patatas y champiñones, en copos', 11, TRUE, 1),
    ('Puré, de patata, con leche', 4, FALSE, 4),
    ('Queso afuega''l pitu', 4, FALSE, 1),
    ('Queso ahumado de aliva', 4, FALSE, 1),
    ('Queso azul', 4, FALSE, 1),
    ('Queso brie', 4, FALSE, 1),
    ('Queso cabra, curado', 4, FALSE, 1),
    ('Queso cabrales', 4, FALSE, 1),
    ('Queso Camembert 20-30% MG/ES', 4, FALSE, 1),
    ('Queso camembert 60% mg/es', 4, FALSE, 1),
    ('Queso cantabria', 4, FALSE, 1),
    ('Queso casín', 4, FALSE, 1),
    ('Queso Castellano', 4, FALSE, 1),
    ('Queso cebreiro', 4, FALSE, 1),
    ('Queso Cheddar', 4, FALSE, 1),
    ('Queso curado, genérico', 4, FALSE, 1),
    ('Queso de aracena', 4, FALSE, 1),
    ('Queso de arzúa', 4, FALSE, 1),
    ('Queso de bola', 4, FALSE, 1),
    ('Queso de cádiz', 4, FALSE, 1),
    ('Queso de Castilla-La Mancha, oveja y cabra', 4, FALSE, 1),
    ('Queso de Castilla-La Mancha, oveja, vaca y cabra', 4, FALSE, 1),
    ('Queso de castilla-león, oveja y vaca', 4, FALSE, 1),
    ('Queso de murcia, al vino', 14, FALSE, 4),
    ('Queso de tenerife', 4, FALSE, 1),
    ('Queso de tiétar', 4, FALSE, 1),
    ('Queso edam', 4, FALSE, 1),
    ('Queso emmental', 9, FALSE, 1),
    ('Queso en porciones', 4, FALSE, 1),
    ('Queso flor de guía', 4, FALSE, 1),
    ('Queso fresco de burgos', 4, FALSE, 1),
    ('Queso fresco, cabra', 4, FALSE, 1),
    ('Queso fresco, desnatado, con frutas', 4, FALSE, 1),
    ('Queso fundido, extragraso (>60% MG/ES)', 4, FALSE, 1),
    ('Queso gata-hurdes', 4, FALSE, 1),
    ('Queso gaztazarra', 4, FALSE, 1),
    ('Queso Gouda', 4, FALSE, 1),
    ('Queso grazalema', 4, FALSE, 1),
    ('Queso Gruyer', 4, FALSE, 1),
    ('Queso herreño', 4, FALSE, 1),
    ('Queso Ibores', 4, FALSE, 1),
    ('Queso Mahón', 4, FALSE, 1),
    ('Queso majorero', 4, FALSE, 1),
    ('Queso manchego', 4, FALSE, 1),
    ('Queso manchego, en aceite', 4, FALSE, 1),
    ('Queso mozzarella', 4, FALSE, 1),
    ('Queso munster', 4, FALSE, 1),
    ('Queso para untar', 4, FALSE, 1),
    ('Queso para untar, con finas hierbas', 4, FALSE, 1),
    ('Queso para untar, con salmón', 4, FALSE, 1),
    ('Queso para untar, natural, bajo en calorías', 4, FALSE, 1),
    ('Queso parmesano', 4, FALSE, 1),
    ('Queso pasiego', 4, FALSE, 1),
    ('Queso pedroches', 4, FALSE, 1),
    ('Queso peñamellera', 4, FALSE, 1),
    ('Queso picón', 4, FALSE, 1),
    ('Queso porrúa', 4, FALSE, 1),
    ('Queso Raclette', 4, FALSE, 1),
    ('Queso rallado, genérico', 4, FALSE, 1),
    ('Queso roquefort', 4, FALSE, 1),
    ('Queso San Simón', 4, FALSE, 1),
    ('Queso semicurado, genérico', 4, FALSE, 1),
    ('Queso serrat', 4, FALSE, 1),
    ('Queso servilleta', 4, FALSE, 1),
    ('Queso Tetilla', 4, FALSE, 1),
    ('Queso tierno, genérico', 4, FALSE, 1),
    ('Queso torta del casar', 4, FALSE, 1),
    ('Queso tupí', 4, FALSE, 1),
    ('Queso Zamorano', 4, FALSE, 1),
    ('Quinoa, cruda', 8, FALSE, 1),
    ('Rábano', 1, FALSE, 1),
    ('Rabo de toro', 2, FALSE, 1),
    ('Rape, a la parrilla', 3, FALSE, 1),
    ('Rape, crudo', 3, FALSE, 1),
    ('Rape, plancha', 3, FALSE, 1),
    ('Raya, cruda', 3, FALSE, 1),
    ('Refresco "tipo gaseosa"', 13, FALSE, 4),
    ('Refresco con gas, sabor cola, sin cafeina', 13, FALSE, 4),
    ('Refresco con gas, sabor cola, sin cafeina, bajo en calorías', 13, FALSE, 4),
    ('Refresco de té', 13, FALSE, 4),
    ('Refresco de té, bajo en calorías', 13, FALSE, 4),
    ('Refresco tipo "tónica"', 13, FALSE, 4),
    ('Refresco, con gas, sabor naranja', 13, FALSE, 4),
    ('Refresco, sabor cola', 13, FALSE, 4),
    ('Refresco, sabor cola, bajo en calorías', 13, FALSE, 4),
    ('Refresco, sabor limón, con gas', 13, FALSE, 4),
    ('Refresco, sabor naranja, sin gas', 13, FALSE, 4),
    ('Regaliz', 15, FALSE, 1),
    ('Remolacha, en conserva', 10, FALSE, 1),
    ('Repollo', 2, FALSE, 1),
    ('Requesón', 4, FALSE, 1),
    ('Riñón, de cordero, crudo', 2, FALSE, 1),
    ('Riñón, de ternera, crudo', 2, FALSE, 1),
    ('Rodaballo', 3, FALSE, 1),
    ('Rollito de primavera', 11, TRUE, 1),
    ('Romero', 9, FALSE, 1),
    ('Ron', 14, FALSE, 4),
    ('Rosquilla', 6, FALSE, 1),
    ('Rúcula', 1, FALSE, 1),
    ('Sal de mar', 9, FALSE, 1),
    ('Sal yodada', 9, FALSE, 1),
    ('Salami', 2, FALSE, 1),
    ('Salchicha de pollo fresca', 2, FALSE, 1),
    ('Salchicha, fresca', 2, FALSE, 1),
    ('Salchicha, tipo "frankfurt"', 2, FALSE, 1),
    ('Salchicha, tipo país, a la plancha', 2, FALSE, 1),
    ('Salchicha, tipo viena', 2, FALSE, 1),
    ('Salchichón', 2, FALSE, 1),
    ('Salema, cruda', 3, FALSE, 1),
    ('Salmón', 3, FALSE, 1),
    ('Salmón ahumado', 3, FALSE, 1),
    ('Salmón, plancha', 3, FALSE, 1),
    ('Salmonete', 3, FALSE, 1),
    ('Salsa agridulce', 9, FALSE, 4),
    ('Salsa al curry', 9, FALSE, 4),
    ('Salsa al roquefort', 9, FALSE, 4),
    ('Salsa barbacoa', 9, FALSE, 4),
    ('Salsa bechamel', 9, FALSE, 4),
    ('Salsa boloñesa', 9, FALSE, 4),
    ('Salsa carbonara', 9, FALSE, 4),
    ('Salsa de queso', 9, FALSE, 4),
    ('Salsa de soja', 9, FALSE, 4),
    ('Salsa napolitana', 9, FALSE, 4),
    ('Salsa siciliana, picante', 9, FALSE, 4),
    ('Salsa vinagreta, con aceite de oliva', 9, FALSE, 4),
    ('Salvado de trigo', 7, FALSE, 1),
    ('San jacobo, congelado', 11, TRUE, 1),
    ('Sandía', 1, FALSE, 1),
    ('Sangría', 14, FALSE, 4),
    ('Sardina', 3, FALSE, 1),
    ('Sardina, asada', 3, FALSE, 1),
    ('Sardina, enlatada, en aceite, escurrida', 10, FALSE, 1),
    ('Sardina, enlatada, en escabeche', 10, FALSE, 1),
    ('Sargo, crudo', 3, FALSE, 1),
    ('Seitán', 8, FALSE, 1),
    ('Semilla de lino', 15, FALSE, 1),
    ('Sémola de trigo, cruda', 7, FALSE, 1),
    ('Sémola de trigo, hervida', 7, FALSE, 1),
    ('Sepia', 3, FALSE, 1),
    ('Sésamo, semilla', 15, FALSE, 1),
    ('Sesos, de cerdo, crudos', 2, FALSE, 1),
    ('Sesos, de cordero, crudos', 2, FALSE, 1),
    ('Sesos, de ternera, crudos', 2, FALSE, 1),
    ('Seta', 1, FALSE, 1),
    ('Seta, plancha', 1, FALSE, 1),
    ('Sidra', 14, FALSE, 4),
    ('Sobao', 6, FALSE, 1),
    ('Sobrasada', 2, FALSE, 1),
    ('Soda', 13, FALSE, 4),
    ('Sofrito', 11, TRUE, 1),
    ('Soja, fresca', 8, FALSE, 1),
    ('Soja, frita', 8, FALSE, 1),
    ('Soja, germinada, en conserva', 10, FALSE, 1),
    ('Soja, seca, cruda', 8, FALSE, 1),
    ('Soja, seca, remojada, hervida', 8, FALSE, 1),
    ('Sopa de sobre maravilla', 11, TRUE, 1),
    ('Sopa de sobre, sin reconstituir', 11, TRUE, 1),
    ('Suplemento proteico', 16, FALSE, 1),
    ('Surimi', 3, FALSE, 1),
    ('Tabasco', 9, FALSE, 1),
    ('Tapioca, hervida', 2, FALSE, 1),
    ('Té, infusión, con leche', 13, FALSE, 4),
    ('Tenca, cruda', 3, FALSE, 1),
    ('Tequila', 14, FALSE, 4),
    ('Ternera, costilla, cruda', 2, FALSE, 1),
    ('Ternera, lomo, crudo, con grasa separable', 2, FALSE, 1),
    ('Ternera, parte s/e, asada', 2, FALSE, 1),
    ('Ternera, parte sin especificar, cruda, con grasa separable', 2, FALSE, 1),
    ('Ternera, solomillo, asado', 2, FALSE, 1),
    ('Ternera, solomillo, sin grasa, crudo', 2, FALSE, 1),
    ('Tocino', 2, FALSE, 1),
    ('Tofu', 8, FALSE, 1),
    ('Tomate', 1, FALSE, 1),
    ('Tomate frito', 1, FALSE, 1),
    ('Tomate, asado', 1, FALSE, 1),
    ('Tomate, maduro, pelado y triturado, enlatado', 10, FALSE, 1),
    ('Tomate, maduro, puré', 1, FALSE, 1),
    ('Tomillo, seco', 9, FALSE, 1),
    ('Torta de aceite', 6, FALSE, 1),
    ('Tortilla, a la francesa', 11, TRUE, 1),
    ('Trigo, entero, crudo', 7, FALSE, 1),
    ('Trucha', 3, FALSE, 1),
    ('Trucha, ahumada', 3, FALSE, 1),
    ('Trufa, cruda', 1, FALSE, 1),
    ('Turrón, tipo Alicante', 15, FALSE, 1),
    ('Uva blanca', 1, FALSE, 1),
    ('Uva blanca, congelada', 1, FALSE, 1),
    ('Uva negra, cruda', 1, FALSE, 1),
    ('Uva pasa', 1, FALSE, 1),
    ('Vaca/buey, parte s/e, asado', 2, FALSE, 1),
    ('Vaca/buey, parte s/e, estofado', 2, FALSE, 1),
    ('Vaca/buey, solomillo, a la plancha', 2, FALSE, 1),
    ('Vaca/buey, solomillo, crudo', 2, FALSE, 1),
    ('Vacuno, hígado, crudo', 2, FALSE, 1),
    ('Vacuno, mollejas, crudas', 2, FALSE, 1),
    ('Vainilla', 9, FALSE, 1),
    ('Vermut, s/e', 14, FALSE, 4),
    ('Vieira', 3, FALSE, 1),
    ('Vieja, cruda', 3, FALSE, 1),
    ('Vinagre balsámico', 9, FALSE, 4),
    ('Vinagre de manzana', 9, FALSE, 4),
    ('Vinagre de vino', 14, FALSE, 4),
    ('Vino blanco', 14, FALSE, 4),
    ('Vino dulce, tipo oporto', 14, FALSE, 4),
    ('Vino rosado', 14, FALSE, 4),
    ('Vino tinto', 14, FALSE, 4),
    ('Vodka', 14, FALSE, 4),
    ('Volador, crudo', 3, FALSE, 1),
    ('Whisky', 14, FALSE, 4),
    ('Yogur griego', 4, FALSE, 1),
    ('Yogur líquido, "tipo actimel"', 4, FALSE, 4),
    ('Yogur líquido, aromatizado sabor s/e', 4, FALSE, 4),
    ('Yogur líquido, con frutas s/e', 4, FALSE, 4),
    ('Yogur líquido, entero, con cereales', 4, FALSE, 4),
    ('Yogur líquido, natural, azucarado', 9, FALSE, 1),
    ('Yogur, búlgaro', 4, FALSE, 1),
    ('Yogur, desnatado, aromatizado sabor s/e', 4, FALSE, 1),
    ('Yogur, desnatado, con cereales', 4, FALSE, 1),
    ('Yogur, desnatado, con cereales, manzana y ciruela', 4, FALSE, 1),
    ('Yogur, desnatado, con cereza y frambuesa', 4, FALSE, 1),
    ('Yogur, desnatado, con ciruela, albaricoque y fibra', 4, FALSE, 1),
    ('Yogur, desnatado, con fresa, grosella y fibra', 4, FALSE, 1),
    ('Yogur, desnatado, con frutas', 4, FALSE, 1),
    ('Yogur, desnatado, con frutas del bosque', 4, FALSE, 1),
    ('Yogur, desnatado, con frutas tropicales', 4, FALSE, 1),
    ('Yogur, desnatado, con manzana', 4, FALSE, 1),
    ('Yogur, desnatado, con melocotón y maracuyá', 4, FALSE, 1),
    ('Yogur, desnatado, con melocotón, frambuesa y fibra', 4, FALSE, 1),
    ('Yogur, desnatado, con piña y pomelo', 4, FALSE, 1),
    ('Yogur, desnatado, sabor natural', 4, FALSE, 1),
    ('Yogur, desnatado, sabor natural, azucarado', 9, FALSE, 1),
    ('Yogur, desnatado, sabor vainilla', 9, FALSE, 1),
    ('Yogur, enriquecido, con frutas', 4, FALSE, 1),
    ('Yogur, enriquecido, natural', 4, FALSE, 1),
    ('Yogur, enriquecido, natural, azucarado', 9, FALSE, 1),
    ('Yogur, enriquecido, natural, con nata', 4, FALSE, 1),
    ('Yogur, enriquecido, sabor, s/e', 4, FALSE, 1),
    ('Yogur, entero, con cereales y fresas', 4, FALSE, 1),
    ('Yogur, entero, con fresas', 4, FALSE, 1),
    ('Yogur, entero, con frutas del bosque', 4, FALSE, 1),
    ('Yogur, líquido, desnatado, natural', 4, FALSE, 4),
    ('Yogur, líquido, entero, con fresas', 4, FALSE, 4),
    ('Yogur, líquido, entero, con frutas', 4, FALSE, 4),
    ('Yogur, líquido, entero, sabor fresa', 4, FALSE, 4),
    ('Yogur, líquido, entero, sabor fresa y plátano', 4, FALSE, 4),
    ('Yogur, líquido, entero, sabor frutas del bosque', 4, FALSE, 4),
    ('Yogur, líquido, entero, sabor piña y coco', 4, FALSE, 4),
    ('Zamburiñas', 3, FALSE, 1),
    ('Zanahoria, cruda', 1, FALSE, 1),
    ('Zumo de grosella negra', 13, FALSE, 4),
    ('Zumo de grosella roja', 13, FALSE, 4),
    ('Zumo de lima, envasado', 13, FALSE, 4),
    ('Zumo de limón, fresco', 13, FALSE, 4),
    ('Zumo de mango', 13, FALSE, 4),
    ('Zumo de manzana', 13, FALSE, 4),
    ('Zumo de naranja', 13, FALSE, 4),
    ('Zumo de piña', 13, FALSE, 4),
    ('Zumo de piña y uva', 13, FALSE, 4),
    ('Zumo de pomelo, envasado', 13, FALSE, 4),
    ('Zumo de tomate, fresco', 13, FALSE, 4),
    ('Zumo de uva', 13, FALSE, 4),
    ('Zumo de uva y melocotón', 13, FALSE, 4),
    ('Zumo de zanahoria, fresco', 13, FALSE, 4)
ON CONFLICT (name) DO NOTHING;
